### Search NaPTAN by bounding box
GET http://localhost:8080/v1/next-departures/search?bbox=-1.565,53.961,-1.503,53.983

### Health check
GET http://localhost:8080/healthz

### Metrics
GET http://localhost:8080/metrics

