CREATE TABLE naptan (
    atco_code VARCHAR(255) PRIMARY KEY,
    naptan_code VARCHAR(255),
    plate_code VARCHAR(255),
    cleardown_code VARCHAR(255),
    common_name TEXT,
    common_name_lang VARCHAR(10),
    short_common_name TEXT,
    short_common_name_lang VARCHAR(10),
    landmark TEXT,
    landmark_lang VARCHAR(10),
    street TEXT,
    street_lang VARCHAR(10),
    crossing TEXT,
    crossing_lang VARCHAR(10),
    indicator TEXT,
    indicator_lang VARCHAR(10),
    bearing VARCHAR(10),
    nptg_locality_code VARCHAR(255),
    locality_name TEXT,
    parent_locality_name TEXT,
    grand_parent_locality_name TEXT,
    town TEXT,
    town_lang VARCHAR(10),
    suburb TEXT,
    suburb_lang VARCHAR(10),
    locality_centre BOOLEAN,
    grid_type VARCHAR(10),
    easting INTEGER,
    northing INTEGER,
    longitude DOUBLE PRECISION,
    latitude DOUBLE PRECISION,
    stop_type VARCHAR(50),
    bus_stop_type VARCHAR(50),
    timing_status VARCHAR(50),
    default_wait_time VARCHAR(50),
    notes TEXT,
    notes_lang VARCHAR(10),
    administrative_area_code VARCHAR(50),
    creation_date_time TIMESTAMP,
    modification_date_time TIMESTAMP,
    revision_number INTEGER,
    modification VARCHAR(50),
    status VARCHAR(50)
);

CREATE INDEX idx_naptan_longitude_latitude ON naptan (Longitude, Latitude);