HTTP/1.1 200 OK
Content-Type: application/xml; charset=utf-8
Transfer-Encoding: chunked
Connection: close
Date: Wed, 29 Apr 2026 20:39:39 GMT
Server-Timing: intid;desc=4c65e1e1380fa7ac
vary: Accept-Encoding, Origin
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Referrer-Policy: strict-origin-when-cross-origin
ETag: W/"9cff8958fd88411933256f14d9c930dc"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: c5fccdfd-6853-48c6-af55-0b37bbdf6be2
X-Runtime: 0.232437
Content-Encoding: gzip
X-Instana-T: 4c65e1e1380fa7ac
X-Instana-S: 4c65e1e1380fa7ac
X-Instana-L: 1
Tracestate: in=4c65e1e1380fa7ac;4c65e1e1380fa7ac
Traceparent: 00-00000000000000004c65e1e1380fa7ac-4c65e1e1380fa7ac-03
X-Cache: Miss from cloudfront
Via: 1.1 6a9ea438bafda34d7b7927bf6f7625fc.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: MAN51-P4
X-Amz-Cf-Id: 3GEvd2pyaA8gMwJxBLX8k5jIyjoxp3urn4UFDx1_LH1ObLh5e8RhmA==

<Siri
  xmlns="http://www.siri.org.uk/" version="1.0">
  <ServiceDelivery>
    <ResponseTimestamp>2026-04-29T21:39:39+01:00</ResponseTimestamp>
    <StopMonitoringDelivery version="1.0">
      <ResponseTimestamp>2026-04-29T21:39:39+01:00</ResponseTimestamp>
      <MonitoredStopVisit>
        <RecordedAtTime>2026-04-29T21:39:39+01:00</RecordedAtTime>
        <MonitoringRef>3200YND13190</MonitoringRef>
        <MonitoredVehicleJourney>
          <FramedVehicleJourneyRef>
            <DataFrameRef>-</DataFrameRef>
            <DatedVehicleJourneyRef>-</DatedVehicleJourneyRef>
          </FramedVehicleJourneyRef>
          <VehicleMode>bus</VehicleMode>
          <PublishedLineName>36</PublishedLineName>
          <DirectionName>Leeds Bus Station</DirectionName>
          <OperatorRef>HRGT</OperatorRef>
          <MonitoredCall>
            <AimedArrivalTime>2026-04-29T21:27:00+01:00</AimedArrivalTime>
            <AimedDepartureTime>2026-04-29T21:27:00+01:00</AimedDepartureTime>
            <ExpectedArrivalTime>2026-04-29T21:45:02+01:00</ExpectedArrivalTime>
            <ExpectedDepartureTime>2026-04-29T21:45:19+01:00</ExpectedDepartureTime>
          </MonitoredCall>
        </MonitoredVehicleJourney>
      </MonitoredStopVisit>
      <MonitoredStopVisit>
        <RecordedAtTime>2026-04-29T21:39:39+01:00</RecordedAtTime>
        <MonitoringRef>3200YND13190</MonitoringRef>
        <MonitoredVehicleJourney>
          <FramedVehicleJourneyRef>
            <DataFrameRef>-</DataFrameRef>
            <DatedVehicleJourneyRef>-</DatedVehicleJourneyRef>
          </FramedVehicleJourneyRef>
          <VehicleMode>bus</VehicleMode>
          <PublishedLineName>36</PublishedLineName>
          <DirectionName>Leeds Bus Station</DirectionName>
          <OperatorRef>HRGT</OperatorRef>
          <MonitoredCall>
            <AimedArrivalTime>2026-04-29T22:27:00+01:00</AimedArrivalTime>
            <AimedDepartureTime>2026-04-29T22:27:00+01:00</AimedDepartureTime>
            <ExpectedArrivalTime>2026-04-29T22:26:58+01:00</ExpectedArrivalTime>
            <ExpectedDepartureTime>2026-04-29T22:26:58+01:00</ExpectedDepartureTime>
          </MonitoredCall>
        </MonitoredVehicleJourney>
        <Extensions>
          <VehicleJourney>
            <SeatedOccupancy>0</SeatedOccupancy>
            <SeatedCapacity></SeatedCapacity>
            <WheelchairOccupancy></WheelchairOccupancy>
            <WheelchairCapacity></WheelchairCapacity>
          </VehicleJourney>
        </Extensions>
      </MonitoredStopVisit>
    </StopMonitoringDelivery>
  </ServiceDelivery>
</Siri>
