INSERT INTO naptan (
    atco_code, naptan_code, plate_code, cleardown_code, common_name, common_name_lang, short_common_name, short_common_name_lang,
    landmark, landmark_lang, street, street_lang, crossing, crossing_lang, indicator, indicator_lang, bearing,
    nptg_locality_code, locality_name, parent_locality_name, grand_parent_locality_name, town, town_lang, suburb, suburb_lang,
    locality_centre, grid_type, easting, northing, longitude, latitude, stop_type, bus_stop_type, timing_status,
    default_wait_time, notes, notes_lang, administrative_area_code, creation_date_time, modification_date_time,
    revision_number, modification, status
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(atco_code) DO UPDATE SET
    naptan_code = excluded.naptan_code,
    plate_code = excluded.plate_code,
    cleardown_code = excluded.cleardown_code,
    common_name = excluded.common_name,
    common_name_lang = excluded.common_name_lang,
    short_common_name = excluded.short_common_name,
    short_common_name_lang = excluded.short_common_name_lang,
    landmark = excluded.landmark,
    landmark_lang = excluded.landmark_lang,
    street = excluded.street,
    street_lang = excluded.street_lang,
    crossing = excluded.crossing,
    crossing_lang = excluded.crossing_lang,
    indicator = excluded.indicator,
    indicator_lang = excluded.indicator_lang,
    bearing = excluded.bearing,
    nptg_locality_code = excluded.nptg_locality_code,
    locality_name = excluded.locality_name,
    parent_locality_name = excluded.parent_locality_name,
    grand_parent_locality_name = excluded.grand_parent_locality_name,
    town = excluded.town,
    town_lang = excluded.town_lang,
    suburb = excluded.suburb,
    suburb_lang = excluded.suburb_lang,
    locality_centre = excluded.locality_centre,
    grid_type = excluded.grid_type,
    easting = excluded.easting,
    northing = excluded.northing,
    longitude = excluded.longitude,
    latitude = excluded.latitude,
    stop_type = excluded.stop_type,
    bus_stop_type = excluded.bus_stop_type,
    timing_status = excluded.timing_status,
    default_wait_time = excluded.default_wait_time,
    notes = excluded.notes,
    notes_lang = excluded.notes_lang,
    administrative_area_code = excluded.administrative_area_code,
    creation_date_time = excluded.creation_date_time,
    modification_date_time = excluded.modification_date_time,
    revision_number = excluded.revision_number,
    modification = excluded.modification,
    status = excluded.status;